# ✔ npm 上生成 x.y.z-alpha.0、x.y.z-alpha.1 等版本
name: publish-alpha

on:
  push:
    branches:
      - release/*-alpha
    paths-ignore:
      - 'package.json'

permissions:
  contents: write

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取所有 commit 和 tag
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build
      - name: Configure git for CI
        run: |
          git config --global user.email "poechiang@live.cn"
          git config --global user.name "poechiang"
      - name: Bump alpha version
        run: |
          npm version prerelease --preid alpha
          git push origin HEAD

      # ⭐ 发布到 npm
      - name: Publish alpha
        run: npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
