# ✔ npm 上生成 1.3.0-beta.1、1.3.0-beta.2 等版本
name: publish-beta

on:
  push:
    branches:
      - release/*-beta
    paths-ignore:
      - 'package.json'

permissions:
  contents: write

jobs:
  release-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取所有 commit 和 tag
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build
      - name: Configure git for CI
        run: |
          git config --global user.email "poechiang@live.cn"
          git config --global user.name "poechiang"
      - name: Bump beta version
        run: |
          npm version prerelease --preid beta
          git push origin HEAD

      # ⭐ 发布到 npm
      - name: Publish beta
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
