# ✔ npm 上生成 1.3.0-beta.1、1.3.0-beta.2 等版本
name: publish-beta

on:
  push:
    branches:
      - release/*-beta
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取所有 commit + tag
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          release-as: '4.1.2-beta.0'
      - name: Publish beta to npm
        run: |
          git config --global user.email "poechiang@live.cn"
          git config --global user.name "poechiang"
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
