name: Release Pre-Release

on:
  push:
    branches:
      - release/*-alpha
      - release/*-beta
      - release/*-rc

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - name: Configure git
        run: |
          git config --global user.email "poechiang@users.noreply.github.com"
          git config --global user.name "poechiang"

      - name: Determine pre-release type
        id: prerelease
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          if [[ "$BRANCH_NAME" =~ -alpha$ ]]; then
            echo "TYPE=alpha" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" =~ -beta$ ]]; then
            echo "TYPE=beta" >> $GITHUB_ENV
          else
            echo "TYPE=rc" >> $GITHUB_ENV
          fi

      - name: Bump version & generate changelog
        run: |
          npm run release:${TYPE}
          git push --follow-tags origin HEAD

      - name: Publish to npm
        run: npm publish --tag ${{ env.TYPE }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
