# ✔ npm 上生成 1.3.0-rc.1、1.3.0-rc.2 等版本
name: publish-rc

on:
  push:
    branches:
      - 'rc/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取所有 commit + tag
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          release-as: '4.1.1-rc.0'
      - name: Publish rc to npm
        run: |
          git config --global user.email "poechiang@live.cn"
          git config --global user.name "poechiang"
          npm publish --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
